### get gradebook list
GET http://localhost:8080/secondary/gradebook

### add gradebook math by post
POST http://localhost:8080/secondary/gradebook/math

### add gradebook math by put
PUT http://localhost:8080/secondary/gradebook/math

###
DELETE http://localhost:8080/secondary/gradebook/1

### add a student grade to gradebook [PUT]
PUT http://localhost:8080/secondary/gradebook/1/student/lili/grade/A+
### add a student grade to gradebook [POST]
POST http://localhost:8080/secondary/gradebook/1/student/jack/grade/B+

### remove student grade
DELETE http://localhost:8080/secondary/gradebook/1/student/jack

###
DELETE http://localhost:8080/secondary/gradebook/1/student/lili

### get gradebook students list
GET http://localhost:8080/secondary/gradebook/1/student

